In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
%matplotlib inline


In [3]:
import sys
sys.path.append('/home/courtney/voxelmorph/src')

import numpy as np
import tensorflow as tf
from losses import normalize

/afs/csail.mit.edu/u/c/courtney/.local/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
def normalize(features):
    mean = tf.reduce_mean(features, axis=(1, 2, 3), keepdims=True)
    var = tf.reduce_mean(tf.square(features - mean), axis=(1,2,3), keepdims=True)
    return (features - mean)/var

In [5]:
def normalize_percentile(features, percentile):
    assert percentile > 50
    top = tf.contrib.distributions.percentile(features, percentile, axis=(0, 4), keep_dims=True)
    bottom = tf.contrib.distributions.percentile(features, 100-percentile, axis=(0, 4), keep_dims=True)
    return (features - bottom)/(top-bottom)

In [6]:
a = [[1, 2, 3, 4], [1, 2, 3, 4]]

In [7]:
b = np.array(a)*2

In [8]:
c = np.array([a, b])

In [9]:
d = np.array([c, 3*c, 2*c])
d.shape

(3, 2, 2, 4)

In [10]:
e = np.array([d])

In [20]:
e.shape

(1, 3, 2, 2, 4)

In [19]:
e

array([[[[[ 1,  2,  3,  4],
          [ 1,  2,  3,  4]],

         [[ 2,  4,  6,  8],
          [ 2,  4,  6,  8]]],


        [[[ 3,  6,  9, 12],
          [ 3,  6,  9, 12]],

         [[ 6, 12, 18, 24],
          [ 6, 12, 18, 24]]],


        [[[ 2,  4,  6,  8],
          [ 2,  4,  6,  8]],

         [[ 4,  8, 12, 16],
          [ 4,  8, 12, 16]]]]])

In [12]:
normalize(e)

<tf.Tensor 'truediv:0' shape=(1, 3, 2, 2, 4) dtype=float64>

In [21]:
top = np.percentile(e, 90, axis=(1,2,3), keepdims=True)
bottom = np.percentile(e, 10, axis=(1,2,3), keepdims=True)

In [22]:
(e-bottom)/(top-bottom)

array([[[[[-0.0212766 , -0.0212766 , -0.0212766 , -0.0212766 ],
          [-0.0212766 , -0.0212766 , -0.0212766 , -0.0212766 ]],

         [[ 0.19148936,  0.19148936,  0.19148936,  0.19148936],
          [ 0.19148936,  0.19148936,  0.19148936,  0.19148936]]],


        [[[ 0.40425532,  0.40425532,  0.40425532,  0.40425532],
          [ 0.40425532,  0.40425532,  0.40425532,  0.40425532]],

         [[ 1.04255319,  1.04255319,  1.04255319,  1.04255319],
          [ 1.04255319,  1.04255319,  1.04255319,  1.04255319]]],


        [[[ 0.19148936,  0.19148936,  0.19148936,  0.19148936],
          [ 0.19148936,  0.19148936,  0.19148936,  0.19148936]],

         [[ 0.61702128,  0.61702128,  0.61702128,  0.61702128],
          [ 0.61702128,  0.61702128,  0.61702128,  0.61702128]]]]])

In [13]:
sess = tf.Session()
with sess.as_default():
    ans = normalize(e).eval()

InternalError: Failed to create session.

In [65]:
ans.shape

(1, 3, 2, 2, 4)

In [63]:
e

array([[[[[ 1,  2,  3,  4],
          [ 1,  2,  3,  4]],

         [[ 2,  4,  6,  8],
          [ 2,  4,  6,  8]]],


        [[[ 3,  6,  9, 12],
          [ 3,  6,  9, 12]],

         [[ 6, 12, 18, 24],
          [ 6, 12, 18, 24]]],


        [[[ 2,  4,  6,  8],
          [ 2,  4,  6,  8]],

         [[ 4,  8, 12, 16],
          [ 4,  8, 12, 16]]]]])

In [66]:
ans

array([[[[[-1.        , -0.4       , -0.25      , -0.19047619],
          [-1.        , -0.4       , -0.25      , -0.19047619]],

         [[-0.5       , -0.2       , -0.125     , -0.0952381 ],
          [-0.5       , -0.2       , -0.125     , -0.0952381 ]]],


        [[[ 0.        ,  0.        ,  0.        ,  0.        ],
          [ 0.        ,  0.        ,  0.        ,  0.        ]],

         [[ 1.5       ,  0.6       ,  0.375     ,  0.28571429],
          [ 1.5       ,  0.6       ,  0.375     ,  0.28571429]]],


        [[[-0.5       , -0.2       , -0.125     , -0.0952381 ],
          [-0.5       , -0.2       , -0.125     , -0.0952381 ]],

         [[ 0.5       ,  0.2       ,  0.125     ,  0.0952381 ],
          [ 0.5       ,  0.2       ,  0.125     ,  0.0952381 ]]]]])

In [56]:
mean = tf.reduce_mean(e, axis=(1, 2, 3), keepdims=True)


In [57]:
mean

<tf.Tensor 'Mean_11:0' shape=(2, 1, 1, 1, 4) dtype=int64>

In [59]:
var = tf.reduce_mean(tf.square(e - mean), axis=(1,2,3), keepdims=True)
var

<tf.Tensor 'Mean_12:0' shape=(2, 1, 1, 1, 4) dtype=int64>

In [ ]:
tf.sqrt()